apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: EFK/apps
    repoURL: 'https://github.com/Brylov/portfolio-infra-argo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true