apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  destination:
    namespace: kube-logging
    server: 'https://kubernetes.default.svc'
  source:
    path: EFK/elasticsearch
    repoURL: 'https://github.com/Brylov/portfolio-infra-argo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
